name: Publish Docker image to Docker Hub

on:
  push:
    branches: [ "main" ] # Trigger the workflow on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: CI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to check out your repository's code

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Use the PAT secret

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Required for advanced features like multi-platform builds

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # The directory containing the Dockerfile (current directory)
          push: true # Push the image to the registry if build is successful
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ci:latest # Tag the image with your Docker Hub repo name and tag

